version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    env_file:
      - .env
    image: frontend
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3001:3000"
